import { shape } from './layers/shape';
import { chars } from './sources/chars';
import { image } from './layers/image';
import { precomp } from './sources/precomp';
import { solid } from './layers/solid';
import { text } from './layers/text';

/**
 * Autogenerated root node for the lootie animations.
 */
export interface LottieModel {
    /**
     * Composition has 3-D layers
     */
    ddd?: number;
    /**
     * Frame Rate
     */
    fr?: number;
    /**
     * Composition Height
     */
    h?: number;
    /**
     * In Point of the Time Ruler. Sets the initial Frame of the animation.
     */
    ip?: number;
    /**
     * Composition name
     */
    nm?: string;
    /**
     * Out Point of the Time Ruler. Sets the final Frame of the animation
     */
    op?: number;
    /**
     * Bodymovin Version
     */
    v?: string;
    /**
     * Composition Width
     */
    w?: number;
    /**
     * List of Composition Layers"
     */
    layers: (shape | solid | precomp | image | null | text)[];
    /**
     * source items that can be used in multiple places. Comps and Images for now.
     */
    assets: (image | precomp)[];
    /**
     * source chars for text layers
     */
    chars: chars[];
}
