export enum SVGElementType {
  svg = "svg",
  g = "g",
  a = "a",
  foreignObject = "foreignObject",
  path = "path",
  rect = "rect",
  circle = "circle",
  ellipse = "ellipse",
  text = "text",
  tspan = "tspan",
  line = "line",
  mesh = "mesh",
  polyline = "polyline",
  polygon = "polygon",
  marker = "marker",
  defs = "defs",
  desc = "desc",
  title = "title",
  /**
   * <symbol> is then mostly suitable for defining reusable elements (or symbols).
   * non visible (having viewBox and preserveAspectRatio attributes,)
   */
  symbol = "symbol",
  use = "use",
  image = "image",
  switch = "switch",
  style = "style",
  unknown = "unknown",
  textpath = "textpath",
  altGlyph = "altglyph",
  altGlyphDef = "altglyphdef",
  altGlyphItem = "altglyphitem",
  glyphRef = "glyphref",
  linearGradient = "lineargradient",
  radialGradient = "radialgradient",
  mask = "mask",
  none = "none",
  doc = "doc",
}
